### ISSUE TITLE
GitHub action for creating releases

### ISSUE THREAD

**Issue by bnonni** [TBD54566975/incubation-dcx#130]
Would like to have a github action to automate the process of creating releases. See example yaml below.

```yaml
name: Create Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Automated release notes for version ${{ github.ref }}.
            - Added feature X
            - Fixed bug Y
          draft: false
          prerelease: false
```
